# Generated by Django 4.2.7 on 2023-11-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.CharField(max_length=5, null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
    ]
